### ISSUE TITLE
Use something more than `setup.py` for packaging

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/text_formatter#17]
`setup.py` is the legacy setup file for setuptools. But maybe we can add a `pyproject.toml` or even a `setup.cfg`. We are going to need a larger discussion on this.

**Comment by DiddiLeija** [comment]
Now, let's see the possibilities:

## :white_check_mark: Using just `setup.py`

It works by now. But `setup.py` is a legacy script, so we might need another solution in the future.

## :white_check_mark: Adding both `setup.cfg` and `setup.py`

It is better than the first option, but `setup.cfg` may cover the same thing than `setup.py`.

## :x: Using just `setup.cfg`

`pip` doesn't give support for setup.cfg-only projects.

## :white_check_mark: Using `pyproject.toml` and `setup.cfg`

This can be the best option for a Python project.

****

I think **option 4** is the best one for us, but we'll need a largerexercise for doing it.

**Comment by DiddiLeija** [comment]
I also consider that _we need eyes_ on this issue. At the moment, it's just me. I can't do a lot by myself.

**Comment by q0w** [comment]
Use setup.cfg + setup.py only

**Comment by DiddiLeija** [comment]
Hey @q0w. thanks for your input! I'm actually planning to do this, but thanks for your opinion!

**Comment by DiddiLeija** [comment]
> using [setup-py-upgrade](https://github.com/asottile/setup-py-upgrade) and [setup-cfg-fmt](https://github.com/asottile/setup-cfg-fmt)

I would like to do it manually, because I think I have to also modify the `setup.py` parameters.

**Comment by DiddiLeija** [comment]
Thanks @q0w! I'll be working on this.

**Comment by DiddiLeija** [comment]
Maybe we should add a `pyproject.toml` in the future, but we don't need it by now.
